name: atoz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  country_picker: ^2.0.15
  country_code_picker: ^2.0.2
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.0.3

  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  intl: ^0.17.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  favorite_button: ^0.0.4
  flutter_speed_dial: ^6.0.0
  image_picker: ^0.8.5+3
  flutter_map: ^2.2.0
  http: ^0.13.5
  url_launcher: ^6.1.5



dev_dependencies:
  flutter_lints: ^2.0.0


  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
